import Head from 'next/head'
import { Layout } from '../Components/Layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind-CSS-Tutorial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout/>
      </main>
    </div>
  )
}
